// src/components/ProjectCard.svelte
<script lang="ts">
    import type { KarbanProjects } from "../types";
    export let project: KarbanProjects;
</script>

<li>
    <div
        class="hover:bg-light-blue-500 hover:border-transparent hover:shadow-lg group block rounded-lg p-4 border border-gray-200">
        <dl
            class="grid sm:block lg:grid xl:block grid-cols-2 grid-rows-2 items-center">
            <div>
                <dt class="sr-only">Title</dt>
                <dd class="leading-6 font-medium text-black">
                    {project.projectName}
                </dd>
            </div>
            <div>
                <dt class="sr-only">Category</dt>
                <dd class="text-sm font-medium sm:mb-4 lg:mb-0 xl:mb-4">
                    {project.projectDescription.substr(0, 25)}...
                </dd>
            </div>
        </dl>
    </div>
</li>

// packages/client/components/ProjectCard.tsx
import { FC } from 'react';
import Link from 'next/link';

interface Props {
  id: string;
  name: string;
  description: string;
}

const ProjectCard: FC<Props> = ({ description, id, name }) => {
  return (
    <Link href={`/project/${id}`}>
      <div className="hover:bg-light-blue-500 hover:border-transparent hover:shadow-lg group block rounded-lg p-4 border border-gray-200">
        <dl className="grid sm:block lg:grid xl:block grid-cols-2 grid-rows-2 items-center">
          <div>
            <dt className="sr-only">Name</dt>
            <dd className="leading-6 font-medium text-black">{name}</dd>
          </div>
          <div>
            <dt className="sr-only">Description</dt>
            <dd className="group-hover:text-light-blue-200 text-sm font-medium sm:mb-4 lg:mb-0 xl:mb-4">
              {description}
            </dd>
          </div>
        </dl>
      </div>
    </Link>
  );
};

export default ProjectCard;
